/**
 * PHD Design System — Tailwind theme extension.
 * Referencia CSS custom properties (--phd-*) — sem valores hardcoded.
 */

/** @type {import('tailwindcss').Config['theme']} */
export const ddsThemeExtend = {
  colors: {
    phd: {
      surface: {
        obsidian: 'var(--phd-surface-obsidian)',
        'obsidian-textured': 'var(--phd-surface-obsidian-textured)',
        'graphite-deep': 'var(--phd-surface-graphite-deep)',
        graphite: 'var(--phd-surface-graphite)',
        'graphite-raised': 'var(--phd-surface-graphite-raised)',
        recessed: 'var(--phd-surface-recessed)',
        'glass-light': 'var(--phd-surface-glass-light)',
        'glass-dark': 'var(--phd-surface-glass-dark)',
        'glass-heavy': 'var(--phd-surface-glass-heavy)',
      },
      text: {
        primary: 'var(--phd-text-primary)',
        secondary: 'var(--phd-text-secondary)',
        tertiary: 'var(--phd-text-tertiary)',
        disabled: 'var(--phd-text-disabled)',
        inverse: 'var(--phd-text-inverse)',
      },
      border: {
        subtle: 'var(--phd-border-subtle)',
        DEFAULT: 'var(--phd-border-default)',
        strong: 'var(--phd-border-strong)',
        accent: 'var(--phd-border-accent)',
      },
      accent: {
        brand: 'var(--phd-accent-brand)',
        'brand-hover': 'var(--phd-accent-brand-hover)',
        'brand-muted': 'var(--phd-accent-brand-muted)',
        creative: 'var(--phd-accent-creative)',
        'creative-hover': 'var(--phd-accent-creative-hover)',
        'creative-muted': 'var(--phd-accent-creative-muted)',
        insights: 'var(--phd-accent-insights)',
        'insights-hover': 'var(--phd-accent-insights-hover)',
        'insights-muted': 'var(--phd-accent-insights-muted)',
        flow: 'var(--phd-accent-flow)',
        'flow-hover': 'var(--phd-accent-flow-hover)',
        'flow-muted': 'var(--phd-accent-flow-muted)',
        dev: 'var(--phd-accent-dev)',
      },
      state: {
        success: 'var(--phd-state-success)',
        'success-muted': 'var(--phd-state-success-muted)',
        warning: 'var(--phd-state-warning)',
        'warning-muted': 'var(--phd-state-warning-muted)',
        error: 'var(--phd-state-error)',
        'error-muted': 'var(--phd-state-error-muted)',
        info: 'var(--phd-state-info)',
        'info-muted': 'var(--phd-state-info-muted)',
      },
      overlay: {
        scrim: 'var(--phd-overlay-scrim)',
        'scrim-heavy': 'var(--phd-overlay-scrim-heavy)',
        hover: 'var(--phd-overlay-hover)',
        active: 'var(--phd-overlay-active)',
        selected: 'var(--phd-overlay-selected)',
      },
      data: {
        live: 'var(--phd-data-live)',
        positive: 'var(--phd-data-positive)',
        negative: 'var(--phd-data-negative)',
        neutral: 'var(--phd-data-neutral)',
      },
    },
  },
  spacing: {
    'phd-0': 'var(--phd-phdu-0)',
    'phd-1': 'var(--phd-phdu-1)',
    'phd-2': 'var(--phd-phdu-2)',
    'phd-3': 'var(--phd-phdu-3)',
    'phd-5': 'var(--phd-phdu-5)',
    'phd-8': 'var(--phd-phdu-8)',
    'phd-13': 'var(--phd-phdu-13)',
    'phd-21': 'var(--phd-phdu-21)',
    'phd-compact': 'var(--phd-padding-compact)',
    'phd-default': 'var(--phd-padding-default)',
    'phd-spacious': 'var(--phd-padding-spacious)',
    'phd-page': 'var(--phd-padding-page)',
    'phd-inline-xs': 'var(--phd-space-inline-xs)',
    'phd-inline-sm': 'var(--phd-space-inline-sm)',
    'phd-inline-md': 'var(--phd-space-inline-md)',
    'phd-stack-xs': 'var(--phd-space-stack-xs)',
    'phd-stack-sm': 'var(--phd-space-stack-sm)',
    'phd-stack-md': 'var(--phd-space-stack-md)',
    'phd-stack-lg': 'var(--phd-space-stack-lg)',
    'phd-stack-xl': 'var(--phd-space-stack-xl)',
    'phd-stack-2xl': 'var(--phd-space-stack-2xl)',
  },
  borderRadius: {
    'phd-none': 'var(--phd-radius-none)',
    'phd-chamfer-sm': 'var(--phd-radius-chamfer-sm)',
    'phd-chamfer-md': 'var(--phd-radius-chamfer-md)',
    'phd-chamfer-lg': 'var(--phd-radius-chamfer-lg)',
    'phd-squircle-sm': 'var(--phd-radius-squircle-sm)',
    'phd-squircle-md': 'var(--phd-radius-squircle-md)',
    'phd-full': 'var(--phd-radius-full)',
  },
  boxShadow: {
    'phd-none': 'var(--phd-shadow-none)',
    'phd-contact': 'var(--phd-shadow-contact)',
    'phd-raised': 'var(--phd-shadow-raised)',
    'phd-elevated': 'var(--phd-shadow-elevated)',
    'phd-accent': 'var(--phd-shadow-accent)',
    'phd-inset': 'var(--phd-shadow-inset)',
    'phd-inset-deep': 'var(--phd-shadow-inset-deep)',
    'phd-focus': 'var(--phd-glow-focus)',
    'phd-glow-processing': 'var(--phd-glow-processing)',
    'phd-glow-live': 'var(--phd-glow-live)',
    'phd-glow-connection': 'var(--phd-glow-connection)',
  },
  blur: {
    'phd-none': 'var(--phd-blur-none)',
    'phd-sm': 'var(--phd-blur-sm)',
    'phd-md': 'var(--phd-blur-md)',
    'phd-lg': 'var(--phd-blur-lg)',
    'phd-xl': 'var(--phd-blur-xl)',
  },
  fontFamily: {
    'phd-display': 'var(--phd-font-display)',
    'phd-body': 'var(--phd-font-body)',
    'phd-mono': 'var(--phd-font-mono)',
  },
  fontSize: {
    'phd-display-xl': ['var(--phd-type-display-xl-size)', { lineHeight: 'var(--phd-type-display-xl-leading)', letterSpacing: 'var(--phd-type-display-xl-tracking)' }],
    'phd-display': ['var(--phd-type-display-size)', { lineHeight: 'var(--phd-type-display-leading)', letterSpacing: 'var(--phd-type-display-tracking)' }],
    'phd-heading-1': ['var(--phd-type-heading-1-size)', { lineHeight: 'var(--phd-type-heading-1-leading)', letterSpacing: 'var(--phd-type-heading-1-tracking)' }],
    'phd-heading-2': ['var(--phd-type-heading-2-size)', { lineHeight: 'var(--phd-type-heading-2-leading)', letterSpacing: 'var(--phd-type-heading-2-tracking)' }],
    'phd-heading-3': ['var(--phd-type-heading-3-size)', { lineHeight: 'var(--phd-type-heading-3-leading)', letterSpacing: 'var(--phd-type-heading-3-tracking)' }],
    'phd-title': ['var(--phd-type-title-size)', { lineHeight: 'var(--phd-type-title-leading)' }],
    'phd-body': ['var(--phd-type-body-size)', { lineHeight: 'var(--phd-type-body-leading)' }],
    'phd-body-sm': ['var(--phd-type-body-sm-size)', { lineHeight: 'var(--phd-type-body-sm-leading)' }],
    'phd-caption': ['var(--phd-type-caption-size)', { lineHeight: 'var(--phd-type-caption-leading)' }],
    'phd-label': ['var(--phd-type-label-size)', { lineHeight: 'var(--phd-type-label-leading)', letterSpacing: 'var(--phd-type-label-tracking)' }],
    'phd-mono': ['var(--phd-type-mono-size)', { lineHeight: 'var(--phd-type-mono-leading)' }],
    'phd-mono-lg': ['var(--phd-type-mono-lg-size)', { lineHeight: 'var(--phd-type-mono-lg-leading)', letterSpacing: 'var(--phd-type-mono-lg-tracking)' }],
  },
  fontWeight: {
    'phd-regular': 'var(--phd-font-weight-regular)',
    'phd-medium': 'var(--phd-font-weight-medium)',
    'phd-semibold': 'var(--phd-font-weight-semibold)',
    'phd-bold': 'var(--phd-font-weight-bold)',
  },
  zIndex: {
    'phd-base': 'var(--phd-z-base)',
    'phd-raised': 'var(--phd-z-raised)',
    'phd-dropdown': 'var(--phd-z-dropdown)',
    'phd-sticky': 'var(--phd-z-sticky)',
    'phd-overlay': 'var(--phd-z-overlay)',
    'phd-modal': 'var(--phd-z-modal)',
    'phd-popover': 'var(--phd-z-popover)',
    'phd-toast': 'var(--phd-z-toast)',
    'phd-tooltip': 'var(--phd-z-tooltip)',
    'phd-max': 'var(--phd-z-max)',
  },
  maxWidth: {
    'phd-wide': 'var(--phd-container-wide)',
    'phd-content': 'var(--phd-container-content)',
    'phd-narrow': 'var(--phd-container-narrow)',
    'phd-micro': 'var(--phd-container-micro)',
  },
  transitionDuration: {
    'phd-instant': 'var(--phd-duration-instant)',
    'phd-fast': 'var(--phd-duration-fast)',
    'phd-normal': 'var(--phd-duration-normal)',
    'phd-slow': 'var(--phd-duration-slow)',
    'phd-transform': 'var(--phd-duration-transform)',
    'phd-continuous': 'var(--phd-duration-continuous)',
  },
  transitionTimingFunction: {
    'phd-default': 'var(--phd-ease-default)',
    'phd-enter': 'var(--phd-ease-enter)',
    'phd-exit': 'var(--phd-ease-exit)',
    'phd-spring': 'var(--phd-ease-spring)',
    'phd-linear': 'var(--phd-ease-linear)',
  },
  transitionDelay: {
    'phd-chain': 'var(--phd-delay-chain)',
    'phd-stagger': 'var(--phd-delay-stagger)',
  },
  animation: {
    'phd-emerge': 'phd-emerge var(--phd-duration-normal) var(--phd-ease-enter) forwards',
    'phd-emerge-subtle': 'phd-emerge-subtle var(--phd-duration-normal) var(--phd-ease-enter) forwards',
    'phd-materialize': 'phd-materialize var(--phd-duration-slow) var(--phd-ease-enter) forwards',
    'phd-recede': 'phd-recede var(--phd-duration-normal) var(--phd-ease-exit) forwards',
    'phd-dissolve': 'phd-dissolve var(--phd-duration-slow) var(--phd-ease-exit) forwards',
    'phd-hex-rotate': 'phd-hex-rotate var(--phd-duration-continuous) var(--phd-ease-linear) infinite',
    'phd-skeleton-pulse': 'phd-skeleton-pulse 1500ms var(--phd-ease-default) infinite',
    'phd-shake-error': 'phd-shake-error var(--phd-duration-fast) linear',
  },
  keyframes: {
    'phd-emerge': {
      from: { opacity: '0', transform: 'translateY(var(--phd-translate-emerge))' },
      to: { opacity: '1', transform: 'translateY(0)' },
    },
    'phd-emerge-subtle': {
      from: { opacity: '0', transform: 'translateY(calc(var(--phd-translate-emerge) / 2))' },
      to: { opacity: '1', transform: 'translateY(0)' },
    },
    'phd-materialize': {
      from: { opacity: '0', transform: 'scale(var(--phd-scale-emerge))' },
      to: { opacity: '1', transform: 'scale(1)' },
    },
    'phd-recede': {
      from: { opacity: '1', transform: 'translateY(0)' },
      to: { opacity: '0', transform: 'translateY(calc(var(--phd-translate-emerge) / -2))' },
    },
    'phd-dissolve': {
      from: { opacity: '1', transform: 'scale(1)' },
      to: { opacity: '0', transform: 'scale(var(--phd-scale-emerge))' },
    },
    'phd-hex-rotate': {
      from: { transform: 'rotate(0deg)' },
      to: { transform: 'rotate(var(--phd-rotate-loading))' },
    },
    'phd-skeleton-pulse': {
      '0%, 100%': { opacity: '0.5' },
      '50%': { opacity: '1' },
    },
    'phd-shake-error': {
      '0%, 100%': { transform: 'translateX(0)' },
      '25%': { transform: 'translateX(calc(var(--phd-shake-error) * -1))' },
      '75%': { transform: 'translateX(var(--phd-shake-error))' },
    },
  },
  screens: {
    'phd-sm': '640px',
    'phd-md': '768px',
    'phd-lg': '1024px',
    'phd-xl': '1280px',
    'phd-2xl': '1536px',
  },
};

export default ddsThemeExtend;
